addons:  
  firefox: latest
language: node_js
node_js:
  - "6"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - au build
script: 
  - npm test
  - sh buildscripts/deploy.sh